### PR TITLE
initialize quarto book and basic structure

### PR DESCRIPTION
**Pull request by mrcaseb**
Ok finally got around setting up the quarto book structure. I am still quite unfamiliar with it so maybe pushed to many files. 

Added an intro trying to describe the scope of the book and added some chapters synchronized with R4DS

### CODE REVIEW

**Comment by mrcaseb** [comment]
yeah I guess the _book directory shouldn't be in git at all

**Comment by tanho63** [comment]
Ooh, sweet! I think the _book subdir is fine, we can just point the GitHub Pages configs at that directory

**Comment by mrcaseb** [comment]
Automate rendering and publish to gh pages https://quarto.org/docs/publishing/github-pages.html

**Comment by tanho63** [comment]
I think `_book` is sufficient for now, perhaps as content increases and/or improves we'll be in a better spot to evaluate whether we want automatic page-build

**Review by tanho63 — APPROVED** [review]
LGTM! I'll probably have some copyediting for the intro/get-started section but think that can happen in subsequent PR.

**Pull request merged**
